name: Deploy
on:
  push:
    branches:
      - 'develop'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn install
      - name: Test
        run: npm run test:ci
      - name: Build
        run: |
          npm run build
          node _tools/generate-post-details-json.js
      - name: Git Identify
        run: |
          git config --global user.email "azuciao@gmail.com"
          git config --global user.name "azu"
      - uses: helaili/jekyll-action@2.5.0
        env:
          JEKYLL_PAT: ${{ secrets.SHARED_BOT_GITHUB_TOKEN }}
        with:
          target_branch: 'master'
